#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["RazorPageApp_2022/RazorPageApp_2022.csproj", "RazorPageApp_2022/"]
RUN dotnet restore "RazorPageApp_2022/RazorPageApp_2022.csproj"
COPY . .
WORKDIR "/src/RazorPageApp_2022"
RUN dotnet build "RazorPageApp_2022.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RazorPageApp_2022.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RazorPageApp_2022.dll"]